<div id='chars' class='w_processor'>
    <div class='notice-wrapper'>
      <div class='notice-header'>
      <span>Maths</span><button class='wbutton' >&nbsp; &cross; &nbsp;</button>
      </div>
      <hr>
      <div class='notice-body'>
<h2>Math Symbols</h2>
<table class="reference">
    <tr>
      <th width="20%" align="left">Character</th>
      <th width="20%" align="left">Entity Number</th>
      <th width="20%" align="left">Entity Name</th>
      <th width="40%" align="left">Description</th>
    </tr>
   <tr>
      <td>&#8704;</td>
      <td>&amp;#8704;</td>
      <td>&amp;forall;</td>
      <td>for all</td>
    </tr>
   <tr>
      <td>&#8706;</td>
      <td>&amp;#8706;</td>
      <td>&amp;part;</td>
      <td>part</td>
    </tr>
   <tr>
      <td>&#8707;</td>
      <td>&amp;#8707;</td>
      <td>&amp;exist;</td>
      <td>exists</td>
    </tr>
   <tr>
      <td>&#8709;</td>
      <td>&amp;#8709;</td>
      <td>&amp;empty;</td>
      <td>empty</td>
    </tr>
   <tr>
      <td>&#8711;</td>
      <td>&amp;#8711;</td>
      <td>&amp;nabla;</td>
      <td>nabla</td>
    </tr>
   <tr>
      <td>&#8712;</td>
      <td>&amp;#8712;</td>
      <td>&amp;isin;</td>
      <td>isin</td>
    </tr>
   <tr>
      <td>&#8713;</td>
      <td>&amp;#8713;</td>
      <td>&amp;notin;</td>
      <td>notin</td>
    </tr>
   <tr>
      <td>&#8715;</td>
      <td>&amp;#8715;</td>
      <td>&amp;ni;</td>
      <td>ni</td>
    </tr>
   <tr>
      <td>&#8719;</td>
      <td>&amp;#8719;</td>
      <td>&amp;prod;</td>
      <td>prod</td>
    </tr>
   <tr>
      <td>&#8721;</td>
      <td>&amp;#8721;</td>
      <td>&amp;sum;</td>
      <td>sum</td>
    </tr>
   <tr>
      <td>&#8722;</td>
      <td>&amp;#8722;</td>
      <td>&amp;minus;</td>
      <td>minus</td>
    </tr>
   <tr>
      <td>&#8727;</td>
      <td>&amp;#8727;</td>
      <td>&amp;lowast;</td>
      <td>lowast</td>
    </tr>
   <tr>
      <td>&#8730;</td>
      <td>&amp;#8730;</td>
      <td>&amp;radic;</td>
      <td>square root</td>
    </tr>
   <tr>
      <td>&#8733;</td>
      <td>&amp;#8733;</td>
      <td>&amp;prop;</td>
      <td>proportional to</td>
    </tr>
   <tr>
      <td>&#8734;</td>
      <td>&amp;#8734;</td>
      <td>&amp;infin;</td>
      <td>infinity</td>
    </tr>
   <tr>
      <td>&#8736;</td>
      <td>&amp;#8736;</td>
      <td>&amp;ang;</td>
      <td>angle</td>
   </tr>
   <tr>
      <td>&#8743;</td>
      <td>&amp;#8743;</td>
      <td>&amp;and;</td>
      <td>and</td>
    </tr>
   <tr>
      <td>&#8744;</td>
      <td>&amp;#8744;</td>
      <td>&amp;or;</td>
      <td>or</td>
    </tr>
   <tr>
      <td>&#8745;</td>
      <td>&amp;#8745;</td>
      <td>&amp;cap;</td>
      <td>cap</td>
    </tr>
   <tr>
      <td>&#8746;</td>
      <td>&amp;#8746;</td>
      <td>&amp;cup;</td>
      <td>cup</td>
    </tr>
   <tr>
      <td>&#8747;</td>
      <td>&amp;#8747;</td>
      <td>&amp;int;</td>
      <td>integral</td>
    </tr>
   <tr>
      <td>&#8756;</td>
      <td>&amp;#8756;</td>
      <td>&amp;there4;</td>
      <td>therefore</td>
    </tr>
   <tr>
      <td>&#8764;</td>
      <td>&amp;#8764;</td>
      <td>&amp;sim;</td>
      <td>similar to</td>
    </tr>
   <tr>
      <td>&#8773;</td>
      <td>&amp;#8773;</td>
      <td>&amp;cong;</td>
      <td>congruent to</td>
    </tr>
   <tr>
      <td>&#8776;</td>
      <td>&amp;#8776;</td>
      <td>&amp;asymp;</td>
      <td>almost equal</td>
    </tr>
   <tr>
      <td>&#8800;</td>
      <td>&amp;#8800;</td>
      <td>&amp;ne;</td>
      <td>not equal</td>
    </tr>
   <tr>
      <td>&#8801;</td>
      <td>&amp;#8801;</td>
      <td>&amp;equiv;</td>
      <td>equivalent</td>
    </tr>
   <tr>
      <td>&#8804;</td>
      <td>&amp;#8804;</td>
      <td>&amp;le;</td>
      <td>less or equal</td>
    </tr>
   <tr>
      <td>&#8805;</td>
      <td>&amp;#8805;</td>
      <td>&amp;ge;</td>
      <td>greater or equal</td>
    </tr>
   <tr>
      <td>&#8834;</td>
      <td>&amp;#8834;</td>
      <td>&amp;sub;</td>
      <td>subset of</td>
    </tr>
   <tr>
      <td>&#8835;</td>
      <td>&amp;#8835;</td>
      <td>&amp;sup;</td>
      <td>superset of</td>
    </tr>
   <tr>
      <td>&#8836;</td>
      <td>&amp;#8836;</td>
      <td>&amp;nsub;</td>
      <td>not subset of</td>
    </tr>
   <tr>
      <td>&#8838;</td>
      <td>&amp;#8838;</td>
      <td>&amp;sube;</td>
      <td>subset or equal</td>
    </tr>
   <tr>
      <td>&#8839;</td>
      <td>&amp;#8839;</td>
      <td>&amp;supe;</td>
      <td>superset or equal</td>
    </tr>
   <tr>
      <td>&#8853;</td>
      <td>&amp;#8853;</td>
      <td>&amp;oplus;</td>
      <td>circled plus</td>
    </tr>
   <tr>
      <td>&#8855;</td>
      <td>&amp;#8855;</td>
      <td>&amp;otimes;</td>
      <td>circled times</td>
    </tr>
   <tr>
      <td>&#8869;</td>
      <td>&amp;#8869;</td>
      <td>&amp;perp;</td>
      <td>perpendicular</td>
    </tr>
   <tr>
      <td>&#8901;</td>
      <td>&amp;#8901;</td>
      <td>&amp;sdot;</td>
      <td>dot operator</td>
    </tr> 
</table>
<hr>
<h2>Greek Letters</h2>
<table class="reference">
    <tr>
      <th width="20%" align="left">Character</th>
      <th width="20%" align="left">Entity Number</th>
      <th width="20%" align="left">Entity Name</th>
      <th width="40%" align="left">Description</th>
    </tr>
    <tr>
      <td>&#913;</td>
      <td>&amp;#913;</td>
      <td>&amp;Alpha;</td>
      <td>Alpha</td>
    </tr>
    <tr>
      <td>&#914;</td>
      <td>&amp;#914;</td>
      <td>&amp;Beta;</td>
      <td>Beta</td>
    </tr>
    <tr>
      <td>&#915;</td>
      <td>&amp;#915;</td>
      <td>&amp;Gamma;</td>
      <td>Gamma</td>
    </tr>
    <tr>
      <td>&#916;</td>
      <td>&amp;#916;</td>
      <td>&amp;Delta;</td>
      <td>Delta</td>
    </tr>
    <tr>
      <td>&#917;</td>
      <td>&amp;#917;</td>
      <td>&amp;Epsilon;</td>
      <td>Epsilon</td>
    </tr>
    <tr>
      <td>&#918;</td>
      <td>&amp;#918;</td>
      <td>&amp;Zeta;</td>
      <td>Zeta</td>
    </tr>
    <tr>
      <td>&#919;</td>
      <td>&amp;#919;</td>
      <td>&amp;Eta;</td>
      <td>Eta</td>
    </tr>
    <tr>
      <td>&#920;</td>
      <td>&amp;#920;</td>
      <td>&amp;Theta;</td>
      <td>Theta</td>
    </tr>
    <tr>
      <td>&#921;</td>
      <td>&amp;#921;</td>
      <td>&amp;Iota;</td>
      <td>Iota</td>
    </tr>
    <tr>
      <td>&#922;</td>
      <td>&amp;#922;</td>
      <td>&amp;Kappa;</td>
      <td>Kappa</td>
    </tr>
    <tr>
      <td>&#923;</td>
      <td>&amp;#923;</td>
      <td>&amp;Lambda;</td>
      <td>Lambda</td>
    </tr>
    <tr>
      <td>&#924;</td>
      <td>&amp;#924;</td>
      <td>&amp;Mu;</td>
      <td>Mu</td>
    </tr>
    <tr>
      <td>&#925;</td>
      <td>&amp;#925;</td>
      <td>&amp;Nu;</td>
      <td>Nu</td>
    </tr>
    <tr>
      <td>&#926;</td>
      <td>&amp;#926;</td>
      <td>&amp;Xi;</td>
      <td>Xi</td>
    </tr>
    <tr>
      <td>&#927;</td>
      <td>&amp;#927;</td>
      <td>&amp;Omicron;</td>
      <td>Omicron</td>
    </tr>
    <tr>
      <td>&#928;</td>
      <td>&amp;#928;</td>
      <td>&amp;Pi;</td>
      <td>Pi</td>
    </tr>
    <tr>
      <td>&#929;</td>
      <td>&amp;#929;</td>
      <td>&amp;Rho;</td>
      <td>Rho</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>undefined</td>
      <td>&nbsp;</td>
      <td>Sigmaf</td>
    </tr>
    <tr>
      <td>&#931;</td>
      <td>&amp;#931;</td>
      <td>&amp;Sigma;</td>
      <td>Sigma</td>
    </tr>
    <tr>
      <td>&#932;</td>
      <td>&amp;#932;</td>
      <td>&amp;Tau;</td>
      <td>Tau</td>
    </tr>
    <tr>
      <td>&#933;</td>
      <td>&amp;#933;</td>
      <td>&amp;Upsilon;</td>
      <td>Upsilon</td>
    </tr>
    <tr>
      <td>&#934;</td>
      <td>&amp;#934;</td>
      <td>&amp;Phi;</td>
      <td>Phi</td>
    </tr>
    <tr>
      <td>&#935;</td>
      <td>&amp;#935;</td>
      <td>&amp;Chi;</td>
      <td>Chi</td>
    </tr>
    <tr>
      <td>&#936;</td>
      <td>&amp;#936;</td>
      <td>&amp;Psi;</td>
      <td>Psi</td>
    </tr>
    <tr>
      <td>&#937;</td>
      <td>&amp;#937;</td>
      <td>&amp;Omega;</td>
      <td>Omega</td>
    </tr>
    
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    
    <tr>
      <td>&#945;</td>
      <td>&amp;#945;</td>
      <td>&amp;alpha;</td>
      <td>alpha</td>
    </tr>
    <tr>
      <td>&#946;</td>
      <td>&amp;#946;</td>
      <td>&amp;beta;</td>
      <td>beta</td>
    </tr>
    <tr>
      <td>&#947;</td>
      <td>&amp;#947;</td>
      <td>&amp;gamma;</td>
      <td>gamma</td>
    </tr>
    <tr>
      <td>&#948;</td>
      <td>&amp;#948;</td>
      <td>&amp;delta;</td>
      <td>delta</td>
    </tr>
    <tr>
      <td>&#949;</td>
      <td>&amp;#949;</td>
      <td>&amp;epsilon;</td>
      <td>epsilon</td>
    </tr>
    <tr>
      <td>&#950;</td>
      <td>&amp;#950;</td>
      <td>&amp;zeta;</td>
      <td>zeta</td>
    </tr>
    <tr>
      <td>&#951;</td>
      <td>&amp;#951;</td>
      <td>&amp;eta;</td>
      <td>eta</td>
    </tr>
    <tr>
      <td>&#952;</td>
      <td>&amp;#952;</td>
      <td>&amp;theta;</td>
      <td>theta</td>
    </tr>
    <tr>
      <td>&#953;</td>
      <td>&amp;#953;</td>
      <td>&amp;iota;</td>
      <td>iota</td>
    </tr>
    <tr>
      <td>&#954;</td>
      <td>&amp;#954;</td>
      <td>&amp;kappa;</td>
      <td>kappa</td>
    </tr>
    <tr>
      <td>&#955;</td>
      <td>&amp;#955;</td>
      <td>&amp;lambda;</td>
      <td>lambda</td>
    </tr>
    <tr>
      <td>&#956;</td>
      <td>&amp;#956;</td>
      <td>&amp;mu;</td>
      <td>mu</td>
    </tr>
    <tr>
      <td>&#957;</td>
      <td>&amp;#957;</td>
      <td>&amp;nu;</td>
      <td>nu</td>
    </tr>
    <tr>
      <td>&#958;</td>
      <td>&amp;#958;</td>
      <td>&amp;xi;</td>
      <td>xi</td>
    </tr>
    <tr>
      <td>&#959;</td>
      <td>&amp;#959;</td>
      <td>&amp;omicron;</td>
      <td>omicron</td>
    </tr>
    <tr>
      <td>&#960;</td>
      <td>&amp;#960;</td>
      <td>&amp;pi;</td>
      <td>pi</td>
    </tr>
    <tr>
      <td>&#961;</td>
      <td>&amp;#961;</td>
      <td>&amp;rho;</td>
      <td>rho</td>
    </tr>
    <tr>
      <td>&#962;</td>
      <td>&amp;#962;</td>
      <td>&amp;sigmaf;</td>
      <td>sigmaf</td>
    </tr>
    <tr>
      <td>&#963;</td>
      <td>&amp;#963;</td>
      <td>&amp;sigma;</td>
      <td>sigma</td>
    </tr>
    <tr>
      <td>&#964;</td>
      <td>&amp;#964;</td>
      <td>&amp;tau;</td>
      <td>tau</td>
    </tr>
    <tr>
      <td>&#965;</td>
      <td>&amp;#965;</td>
      <td>&amp;upsilon;</td>
      <td>upsilon</td>
    </tr>
    <tr>
      <td>&#966;</td>
      <td>&amp;#966;</td>
      <td>&amp;phi;</td>
      <td>phi</td>
    </tr>
    <tr>
      <td>&#967;</td>
      <td>&amp;#967;</td>
      <td>&amp;chi;</td>
      <td>chi</td>
    </tr>
    <tr>
      <td>&#968;</td>
      <td>&amp;#968;</td>
      <td>&amp;psi;</td>
      <td>psi</td>
    </tr>
    <tr>
      <td>&#969;</td>
      <td>&amp;#969;</td>
      <td>&amp;omega;</td>
      <td>omega</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>&#977;</td>
      <td>&amp;#977;</td>
      <td>&amp;thetasym;</td>
      <td>theta symbol</td>
    </tr>
    <tr>
      <td>&#978;</td>
      <td>&amp;#978;</td>
      <td>&amp;upsih;</td>
      <td>upsilon symbol</td>
    </tr>
    <tr>
      <td>&#982;</td>
      <td>&amp;#982;</td>
      <td>&amp;piv;</td>
      <td>pi symbol</td>
    </tr>
</table>

      </div>
      <div class='notice-footer'>
      <button class='wbutton' >&nbsp; &cross; &nbsp;</button>
      </div>
    </div>
</div>